name: 'Publish Electron App'

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            args: '--linux'
          - os: macos-latest
            args: '--mac'
          - os: windows-latest
            args: '--win'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build frontend assets using Vite
      - name: Build Vite assets
        run: yarn vite build

      # Package the Electron app for the specific platform
      - name: Package Electron App
        run: yarn electron-builder ${{ matrix.args }}

      # Upload build artifacts (release assets)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release/${{ steps.version.outputs.version }}/*

      # Create a draft release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/${{ steps.version.outputs.version }}/*
          draft: true
          prerelease: false
